### ISSUE TITLE
Erreur filebot

### ISSUE THREAD

**Issue by laster13** [xataz/docker-rtorrent-rutorrent#31]
Bonjour, il apparaît que depuis quelques commit (celui du 29/03/2019), filebot ne fonctionne plus avec une erreur java

```
null
java.lang.ExceptionInInitializerError
        at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
        at net.filebot.CachedResource.lambda$fetchIfModified$9(CachedResource.java:215)
        at net.filebot.CachedResource.lambda$null$0(CachedResource.java:87)
        at net.filebot.CachedResource.retry(CachedResource.java:121)
        at net.filebot.CachedResource.lambda$get$1(CachedResource.java:87)
        at net.filebot.Cache.computeIf(Cache.java:90)
        at net.filebot.CachedResource.get(CachedResource.java:82)
        at net.filebot.MemoizedResource.get(Resource.java:36)
        at net.filebot.cli.ScriptBundle.getScript(ScriptBundle.java:32)
        at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:74)
        at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:119)
        at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:29)
        at net.filebot.Main.main(Main.java:115)
Caused by: java.security.ProviderException: Could not initialize NSS
        ... 13 more
Caused by: java.io.FileNotFoundException: /usr/lib/libnss3.so
        ... 13 more

Failure (°_°)

```` 

Merci de ton travail @xataz

**Comment by xataz** [comment]
Je regarde ça ce soir, y'a pas mal de bug depuis la mise à jour

**Comment by djerfy** [comment]
> Je regarde ça ce soir, y'a pas mal de bug depuis la mise à jour

👍 Merci. Normalement c'est dans le package `nss` qui est requis lorsque tu install `openjdk8-jre`, bizarre que ce ne soit pas pris en compte...

**Comment by xataz** [comment]
Je viens de pousser une modification, mais je ne peux pas tester pour le moment

**Comment by PixiBixi** [comment]
Testé de mon côté, c'est ok, merci pour le fix.

Cependant, petit (autre) problème : 

```
[08.04.2019 13:56:51] cloudflare: Cant load cfscrape, python
[08.04.2019 13:56:52] Python Not Found
```

Soit virer le plugin cloudflare, soit ajouter python ;)

**Comment by xataz** [comment]
ça en fait de la régression, sans grande modification de mon coté en plus.

Je viens d'ajouter python, et l'installation du package python cfscrape. Normalement ça devrait marcher.

**Comment by PixiBixi** [comment]
Clairement...

Je refais un pull, je te tiens au courant.

**Comment by xataz** [comment]
Pas utile pour toi ou moi, mais certainement utile pour certain.
Comme geoip, perso je ne l'utilise pas, mais certains oui.
