### ISSUE TITLE
Mbstring is missing

### ISSUE THREAD

**Issue by PixiBixi** [xataz/docker-rtorrent-rutorrent#5]
Plop xataz !

Petit bug qui apparait de manière aléatoire (Mais chiant quand ça arrive)

```
2017/08/06 17:48:24 [error] 40#40: *80 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_strlen() in /var/www/html/torrent/plugins/_task/task.php:142
Stack trace:
#0 /var/www/html/torrent/plugins/_task/task.php(155): rTask::tail('/var/www/html/t...')
#1 /var/www/html/torrent/plugins/_task/task.php(210): rTask::processLog('/var/www/html/t...', 'log', Array, 0, 0)
#2 /var/www/html/torrent/plugins/_task/task.php(280): rTask::check('15020188955986f...')
#3 /var/www/html/torrent/plugins/_task/task.php(306): rTaskManager::obtain()
#4 /var/www/html/torrent/plugins/_task/init.php(5): rTaskManager::cleanup()
#5 /var/www/html/torrent/php/getplugins.php(495): require_once('/var/www/html/t...')
#6 {main}
  thrown in /var/www/html/torrent/plugins/_task/task.php on line 142" while reading response header from upstream, client: 172.18.0.5, server: _, request: "GET /php/getplugins.php
HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "x", referrer: "https://x/"
```

Rien de bien méchant, il est apparu quand une personne a essayée d'ajouter un gros torrent.

Ajoute php7-mbstring à ton image stp :)

**Comment by xataz** [comment]
C'est bon
